import os

from snakemake.utils import min_version

min_version('8.11')


include: 'rules/resources.smk'
include: 'rules/identification.smk'
include: 'rules/mapping.smk'
# include: 'rules/phylogeny.smk'