import os

from snakemake.utils import min_version

min_version('8.11')


include: 'rules/resources.smk'


rule all:
    input:
        'data/samplesheet.duckdb',
        'resources/samplesheets/main.csv',
    localrule: True