duckdbrc_slurm: /raven/u/thosi/dev/projects/wide-variant/config/duckdbrc-slurm

# Directories for 'permament', global data stores
directories:
  data: /raven/ptmp/thosi/baby-biome/data
  resources: /raven/ptmp/thosi/baby-biome/resources

wildcards:
  # TODO: Name collision (so need to add key_k2db)
  db_name: identification_cache|mapping_cache|reference_genomes|samplesheet|key_k2db
  genomes: Bacteroides_xylanisolvens|Bifidobacterium_adolescentis|Bifidobacterium_bifidum|Bifidobacterium_longum|Enterococcus_faecalis|Escherichia_coli|Klebsiella_oxytoca|Staphylococcus_aureus
  library: 20241105_AV234501_B-PE75-Ad-HiO|230119_B001_Lib|230913_B002_B001_Lib|240704_B002_B001_Lib_AVITI_reseq
  resource: fastqs|samples|sequencing
  # NOTE: These are the plate ID-ed species. Options:
  #       Bacteroides_xylanisolvens|Bifidobacterium_spp|Enterococcus_faecalis|Escherichia_coli|Klebsiella_oxytoca|Staphylococcus_aureus
  species_stdized: Bifidobacterium_spp|Escherichia_coli

pipeline_artifacts:
  bracken:
    glob: /raven/ptmp/thosi/baby-biome/data/identification/tool=taxprofiler/**/*.bracken.parquet
    fields: tool|taxon_db|family|id|library|sample
    pat: tool=(.*)/db=(.*)/family=(.*)/id=(.*)/library=(.*)/(.*).bracken.parquet

  bracken_raw:
    glob: results/taxprofiler/bracken/*/*_*_*.bracken.tsv
    fields: taxon_db|sample
    pat: bracken/(.*)/(\d+)_\d+_.*.bracken.tsv

  srst2:
    glob: /raven/ptmp/thosi/baby-biome/data/identification/tool=srst2/**/*.txt
    fields: tool|species|family|id|library|sample
    pat: tool=(.*)/db=(.*)/family=(.*)/id=(.*)/library=(.*)/(.*).txt

tools:
  # Options: srst2|taxprofiler
  identification: srst2|taxprofiler
  # Options: bactmap|sarek_bcftools|sarek_freebayes|sarek_haplotypecaller|snippy
  mapping: bactmap|sarek_bcftools|sarek_freebayes|sarek_haplotypecaller|snippy