from snakemake.utils import min_version

min_version('8.26')


envvars:
    'TMPDIR',


configfile: workflow.source_path('../../config/data.json')
configfile: workflow.source_path('../../config/public_data.json')
configfile: workflow.source_path('../../config/params.yaml')


wildcard_constraints:
    db_name=config['wildcards']['db_name'],
    family=r'B\d+',
    id=r'B\d+_\d+',
    library=config['wildcards']['library'],
    resource=config['wildcards']['resource'],
    sample=r'\d+',
    species=config['wildcards']['genomes']


include: '../utils/common.smk'
include: 'rules/resources.smk'
include: 'rules/analysis.smk'


rule all:
    input:
        'resources/samplesheet-with-ref.csv',
    default_target: True